### ISSUE TITLE
not working outside of tmux (probably doing something wrong)

### ISSUE THREAD

**Issue by AdamBD** [declancm/windex.nvim#5]
This is my installation:

```
	{
		'declancm/windex.nvim',
		config = function()
			require('windex').setup({
				default_keymaps = false, -- Enable default keymaps.
			})
		end
	},

```

and my invocation

```
keymap('n', '<Leader>m', "<Cmd>lua require('windex').toggle_maximize()<CR>", default_opts)
```

I get this error:
`Error: Tmux 1.8+ is required. Use 'maximize_nvim_window()' instead or install/update Tmux`

**Comment by gabsrp2002** [comment]
# Solution
Just use `toggle_nvim_maximize()` instead of `toggle_maximize()` and it should work fine. 

# Explanation
In the README file it's said that the `toggle_maximize()` function is used to maximize both the neovim window and the tmux pane, so you **need** tmux to use it. That's why you are getting an error saying you do not have tmux installed.

Also, you should consider using [this plugin](https://github.com/declancm/maximize.nvim) for just the maximization feature (it's also recommended in the README).

**Comment by declancm** [comment]
Thanks @gabsrp2002 your answer was perfect.  I'll try to improve error messages like that one in the near future
